### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by fiveorders** [modern-hobbyist/modern-snippets#1]
First of all, thank you for this valuable work. I watched the Youtube video and did whatever you showed. The script for saving on Raspberry sort of works, it takes snapshots however, gives the error below. I also added the high quality option script but that doesn't work. both files chmod enabled. Any Ideas? My Camera is Canon R5 and it is compatible.

<img width="396" alt="Screenshot 2021-06-27 at 11 35 54" src="https://user-images.githubusercontent.com/13808989/123541377-298c4400-d73c-11eb-921a-8284184eeed0.png">

```
2021-06-26 16:02:19,639 - octolapse.__init__ - INFO - Started logging to file.
2021-06-26 16:02:19,848 - octolapse.settings - INFO - Creating settings from iterable.
2021-06-26 16:02:19,924 - octolapse.settings - INFO - Settings created from iterable.
2021-06-26 16:02:19,960 - octolapse.settings - INFO - Default settings loaded.
2021-06-26 16:01:32,431 - octolapse.__init__ - INFO - Started logging to file.
2021-06-26 16:01:32,462 - octolapse.settings - INFO - Loading existing settings file from: /home/pi/.octoprint/data/octolapse/settings.json.
2021-06-26 16:01:32,607 - octolapse.settings - INFO - Creating settings from iterable.
2021-06-26 16:01:33,032 - octolapse.settings - INFO - Settings created from iterable.
2021-06-26 16:01:33,078 - octolapse.settings - INFO - Settings file loaded.
2021-06-27 11:25:53,960 - octolapse.script - ERROR - An error occurred while executing 'DSLR - Snapshot Camera Script'
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/script.py", line 248, in execute_process
    self.proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/pi/scripts/take-snapshot.sh'
2021-06-27 11:29:40,616 - octolapse.script - ERROR - An error occurred while executing 'DSLR - Snapshot Camera Script'
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/script.py", line 248, in execute_process
    self.proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/pi/scripts/take-snapshot.sh'
2021-06-27 11:31:32,385 - octolapse.script - ERROR - Error output (stderr) for 'DSLR - Snapshot Camera Script':
	ERROR: Could not get image.
2021-06-27 11:33:11,294 - octolapse.script - ERROR - Error output (stderr) for 'DSLR - Snapshot Camera Script':
	ERROR: Could not get image.
2021-06-27 11:35:08,175 - octolapse.script - ERROR - Error output (stderr) for 'DSLR - Snapshot Camera Script':
	ERROR: Could not get image.
2021-06-27 11:35:32,831 - octolapse.script - ERROR - Error output (stderr) for 'DSLR - Snapshot Camera Script':
	ERROR: Could not get image.
2021-06-27 11:36:10,302 - octolapse.script - ERROR - Error output (stderr) for 'DSLR - Snapshot Camera Script':
	ERROR: Could not get image.
2021-06-27 11:36:32,196 - octolapse.script - ERROR - Error output (stderr) for 'DSLR - Snapshot Camera Script':
	ERROR: Could not get image.

```

**Comment by fiveorders** [comment]
And these are the logs with DSLR SD Script


```
2021-06-26 16:02:19,639 - octolapse.__init__ - INFO - Started logging to file.
2021-06-26 16:02:19,848 - octolapse.settings - INFO - Creating settings from iterable.
2021-06-26 16:02:19,924 - octolapse.settings - INFO - Settings created from iterable.
2021-06-26 16:02:19,960 - octolapse.settings - INFO - Default settings loaded.
2021-06-26 16:01:32,431 - octolapse.__init__ - INFO - Started logging to file.
2021-06-26 16:01:32,462 - octolapse.settings - INFO - Loading existing settings file from: /home/pi/.octoprint/data/octolapse/settings.json.
2021-06-26 16:01:32,607 - octolapse.settings - INFO - Creating settings from iterable.
2021-06-26 16:01:33,032 - octolapse.settings - INFO - Settings created from iterable.
2021-06-26 16:01:33,078 - octolapse.settings - INFO - Settings file loaded.
2021-06-27 11:25:53,960 - octolapse.script - ERROR - An error occurred while executing 'DSLR - Snapshot Camera Script'
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/script.py", line 248, in execute_process
    self.proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/pi/scripts/take-snapshot.sh'
2021-06-27 11:29:40,616 - octolapse.script - ERROR - An error occurred while executing 'DSLR - Snapshot Camera Script'
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/script.py", line 248, in execute_process
    self.proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/pi/scripts/take-snapshot.sh'
2021-06-27 11:31:32,385 - octolapse.script - ERROR - Error output (stderr) for 'DSLR - Snapshot Camera Script':
	ERROR: Could not get image.
2021-06-27 11:33:11,294 - octolapse.script - ERROR - Error output (stderr) for 'DSLR - Snapshot Camera Script':
	ERROR: Could not get image.
2021-06-27 11:35:08,175 - octolapse.script - ERROR - Error output (stderr) for 'DSLR - Snapshot Camera Script':
	ERROR: Could not get image.
2021-06-27 11:35:32,831 - octolapse.script - ERROR - Error output (stderr) for 'DSLR - Snapshot Camera Script':
	ERROR: Could not get image.
2021-06-27 11:36:10,302 - octolapse.script - ERROR - Error output (stderr) for 'DSLR - Snapshot Camera Script':
	ERROR: Could not get image.
2021-06-27 11:36:32,196 - octolapse.script - ERROR - Error output (stderr) for 'DSLR - Snapshot Camera Script':
	ERROR: Could not get image.
2021-06-27 11:40:40,635 - octolapse.script - ERROR - An error occurred while executing 'DSLR SD - Snapshot Camera Script'
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/script.py", line 248, in execute_process
    self.proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/pi/scripts/take-snapshot-to-sd.sh'
2021-06-27 11:40:59,503 - octolapse.script - ERROR - An error occurred while executing 'DSLR SD - Snapshot Camera Script'
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/script.py", line 248, in execute_process
    self.proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/scripts/take-snapshot-to-sd.sh'
2021-06-27 11:41:00,768 - octolapse.script - ERROR - An error occurred while executing 'DSLR SD - Snapshot Camera Script'
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/script.py", line 248, in execute_process
    self.proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/scripts/take-snapshot-to-sd.sh'
2021-06-27 11:41:39,146 - octolapse.script - ERROR - An error occurred while executing 'DSLR SD - Snapshot Camera Script'
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/script.py", line 248, in execute_process
    self.proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/scripts/take-snapshot-to-sd.sh'
2021-06-27 11:41:58,378 - octolapse.script - ERROR - Error output (stderr) for 'DSLR - Snapshot Camera Script':
	ERROR: Could not get image.
2021-06-27 11:42:10,716 - octolapse.script - ERROR - An error occurred while executing 'DSLR SD - Snapshot Camera Script'
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/script.py", line 248, in execute_process
    self.proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/scripts/take-snapshot-to-sd.sh'
2021-06-27 11:44:19,921 - octolapse.script - ERROR - An error occurred while executing 'DSLR SD - Snapshot Camera Script'
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/script.py", line 248, in execute_process
    self.proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/scripts/take-snapshot-to-sd.sh'
2021-06-27 11:33:23,703 - octolapse.__init__ - INFO - Started logging to file.
2021-06-27 11:33:23,712 - octolapse.settings - INFO - Loading existing settings file from: /home/pi/.octoprint/data/octolapse/settings.json.
2021-06-27 11:33:23,745 - octolapse.settings - INFO - Creating settings from iterable.
2021-06-27 11:33:23,800 - octolapse.settings - INFO - Settings created from iterable.
2021-06-27 11:33:23,801 - octolapse.settings - INFO - Settings file loaded.
2021-06-27 11:50:39,009 - octolapse.script - ERROR - An error occurred while executing 'DSLR SD - Snapshot Camera Script'
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/script.py", line 248, in execute_process
    self.proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/scripts/take-snapshot-to-sd.sh'
2021-06-27 11:50:43,725 - octolapse.script - ERROR - Error output (stderr) for 'DSLR - Snapshot Camera Script':
	ERROR: Could not get image.
2021-06-27 11:52:35,955 - octolapse.script - ERROR - An error occurred while executing 'DSLR SD - Snapshot Camera Script'
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse/script.py", line 248, in execute_process
    self.proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/scripts/take-snapshot-to-sd.sh'
2021-06-27 11:52:39,513 - octolapse.script - ERROR - Error output (stderr) for 'DSLR - Snapshot Camera Script':
	ERROR: Could not get image.

```
